---
# tasks file for hoplacloud.wordpress

- name: Ensure root password is allowed in SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: "PermitRootLogin yes"

- name: restart service ssh
  systemd:
    state: restarted
    name: ssh

- name: Init vars
  set_fact:
    wp_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits,hexdigits') }}"
    db_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}"
    db_root_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,hexdigits') }}"
    vhost_user: "{{ vhost_url | regex_replace('\\.') | truncate(13, True, '') }}"
    vhost_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,hexdigits') }}"
    vhost_domain: "{{ vhost_url | regex_replace('([^\\.]*)\\.(.+)$', '\\2') }}"
    vhost_sdomain: "{{ vhost_url | regex_replace('([^\\.]*)\\.(.+)$', '\\1') }}"

- name: Create compose directory
  file:
    path: /root/compose/wordpress
    state: directory

- name: Create compose apache2 directory
  file:
    path: /root/compose/wordpress/apache2
    state: directory

- name: Create container directory
  file:
    path: /var/container
    state: directory

- name: Create container directory
  file:
    path: /var/container/wordpress
    state: directory

- name: Create container directory
  file:
    path: /var/container/wordpress/etc
    state: directory

- name: Create container directory
  file:
    path: /var/container/wordpress/etc/apache2
    state: directory

- name: Create container directory
  file:
    path: /var/container/wordpress/etc/apache2/conf
    state: directory

- name: Create container directory
  file:
    path: /var/container/wordpress/etc/traefik
    state: directory

- name: Copy Dockerfile for apache2
  copy:
    src: Dockerfile_apache2.yml
    dest: /root/compose/wordpress/apache2/Dockerfile.yml

- name: Create docker-compose file
  template:
    src: docker-compose.j2
    dest: /root/compose/wordpress/docker-compose.yml

- name: Copy config for apache2
  copy:
    src: apache2/php-fpm.conf
    dest: /var/container/wordpress/etc/apache2/conf/php-fpm.conf

- name: Create traefik config file
  template:
    src: traefik.j2
    dest: /var/container/wordpress/etc/traefik/traefik.toml

- name: Set vhost_path
  set_fact:
    vhost_path: "/var/www/custs/{{ vhost_domain }}/{{ vhost_sdomain }}"
    vhost_conf_file: "{{ vhost_domain }}_{{ vhost_sdomain }}"

- name: Run docker compose
  docker_compose:
    project_name: wordpress
    project_src: /root/compose/wordpress

- name: Log variables to file
  template:
    src: logs.j2
    dest: /root/Oneclick-wp-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.txt
    owner: root
    group: root

- name: Display root password in case of mail delivery failure
  debug:
    msg: root password is {{ root_password }}

- name: Sending end of provisionning Email to user
  mail:
    host: localhost
    port: 25
    to: "{{ user_email }}"
    subject: "hopla.cloud : 👏 Votre {{ app_name }} vous attend !"
    subtype: "html"
    secure: "never"
    body: '
    <p>
    {{ app_name }}<br>
    http://{{ vhost_url }} <br>
    Utilisateur: admin <br>
    Mot de passe: {{ wp_password }} <br>
    Acces admin : http://{{ vhost_url }}/wp-admin/ <br>
    </p>
    <p>
    FTP <br>
    ftp://{{ vhost_url }} <br>
    Utilisateur: {{ vhost_user }} <br>
    Mot de passe: {{ vhost_password }} <br>
    </p>
    <p>
    SSH <br>
    IPv4: {{ ansible_default_ipv4.address }}<br>
    IPv6: {{ ansible_default_ipv6.address }}<br>
    Utilisateur: root<br>
    Mot de passe: {{ root_password }} <br>
    </p>
    '
